import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import NavBar from "./NavBar";

interface LayoutProps {
  children: React.ReactNode;
}
const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>YFK - Ylivieskan Frisbeekarhut Ry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="w-screen">{children}</main>
      <Footer />
    </>
  );
};
export default Layout;
