import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import NavBar from "./NavBar";

interface LayoutProps {
  children: React.ReactNode;
}
const Layout = ({ children }: LayoutProps) => {
  return (
    <div className="flex flex-col h-screen justify-between">
      <Head>
        <title>YFK - Ylivieskan Frisbeekarhut Ry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="mb-auto">{children}</main>
      <Footer />
    </div>
  );
};
export default Layout;
